#pragma once

#define SHADOW_IMPL_MASTER 0
#define SHADOW_IMPL_BASIC 1
#define SHADOW_IMPL_PCF 2
#define SHADOW_IMPL_VSM 3
#define SHADOW_IMPL_PCSS 4
#define SHADOW_IMPL_CHSS 5

#define SHADOW_IMPL SHADOW_IMPL_MASTER

#ifndef SHADOW_IMPL
#error "SHADOW_IMPL is not defined!"
#endif

#if SHADOW_IMPL < SHADOW_IMPL_MASTER || SHADOW_IMPL > SHADOW_IMPL_CHSS
#error "Invalid SHADOW_IMPL value!"
#endif

#define SHADOW_MASTER SHADOW_IMPL == SHADOW_IMPL_MASTER
#define SHADOW_BASIC SHADOW_IMPL == SHADOW_IMPL_BASIC
#define SHADOW_PCF SHADOW_IMPL == SHADOW_IMPL_PCF
#define SHADOW_VSM SHADOW_IMPL == SHADOW_IMPL_VSM
#define SHADOW_PCSS SHADOW_IMPL == SHADOW_IMPL_PCSS
#define SHADOW_CHSS SHADOW_IMPL == SHADOW_IMPL_CHSS
